resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/reel010/bp.git
      branch: main

jobs:
  - name: run-btc-price
    public: true
    plan:
      - get: repo
        trigger: true
      - task: execute-btc-price
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.11"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -exc
              - |
                pip install --upgrade pip
                pip install -r repo/requirements.txt
                python repo/btcprice.py
