resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/reel010/bp.git
      branch: main  # Adjust if you're using a different branch

jobs:
  - name: run-btc-price
    public: true
    plan:
      - get: repo
        trigger: true
      - task: execute-btc-price
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"  # Use the Python version matching your script
          inputs:
            - name: repo
          run:
            path: python
            args:
              - repo/btcprice.py